### ISSUE TITLE
Sir, how to use this toolkit to plot this picture that has lots of PSDs?

### ISSUE THREAD

**Issue by lhyxyw** [iris-edu/noise-toolkit#5]
Sir, When I plot the picture,just like this
![Figure_1](https://github.com/iris-edu/noise-toolkit/assets/114545948/f323a16e-5e3a-4eb3-b0f6-8dc93656370c)

But I want to plot picture like this:
![捕获12](https://github.com/iris-edu/noise-toolkit/assets/114545948/dc2850cf-a469-4395-912e-6c396045142e)

Sir ,could you tell me how to use the toolkit to get it?

Best Wishes!

**Comment by manoch-iris** [comment]
Dear @lhyxyw,

The noise toolkit does the computation and provides data. The plotting capabilities provided are limited and are only for validating data. Because of that, we do not provide the plotting tools you are looking for. You need to use the data files that NTK generates and your own code or other packages to create a detailed plot. Sorry, couldn’t help.

Best,
--manoch
